name: Build Flutter Debug APK

on:
  push:
    branches:
      - deploy_test_branch
  pull_request:
    branches:
      - deploy_test_branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          cache: false

      - name: Install dependencies
        run: flutter pub get

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
